services:
  db:
    image: mysql:8.0
    container_name: dreamvacation-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Fa369852
      MYSQL_DATABASE: dreamvacation
    ports:
      - "3307:3306"  # Changed from 3308 to 3306 for default MySQL compatibility
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: dreamvacation-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://root:Fa369852@db:3306/dreamvacation
      PORT: 3001
      COUNTRIES_API_BASE_URL: https://restcountries.com/v3.1
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: dreamvacation-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - backend
volumes:
  db_data:
